### PR TITLE
Add a slack notification for bugs that don't have a cause

### LINKED ISSUE #45: Notify if a bug is moved to a status after development without a bug cause
- If an issue is moved to a status after development (e.g. review, functional review, released)
- And it is a bug
- And it has an empty bug cause
- Notify the developer

### PR DESCRIPTION
**Pull request by rchampourlier**
New type of trigger - an issue that is updated but as it’s a bug, it
needs a bug_cause, and it’s not the case. So, a Slack notification is
sent to the assigned developer to change this sad situation.
Tests coming up.

Fixes #45

### CODE REVIEW

File: lib/job_tomate/actions/slack_notify_jira_bug_issue_without_cause_updated.rb [hunk 1]
```diff
@@ -0,0 +1,30 @@
+require "data/user"
+require "support/service_pattern"
+
+module JobTomate
+  module Actions
+
+    # Notifies the JIRA issue's assignee on Slack.
+    class SlackNotifyJIRABugIssueWithoutCauseUpdated
```
Comment (rchampourlier) [inline lib/job_tomate/actions/slack_notify_jira_bug_issue_without_cause_updated.rb]: Wouldn't `SlackNotifyJIRABugIssueUpdatedWithoutCause` be more readable?

File: lib/job_tomate/triggers/webhooks/jira.rb [hunk 2]
```diff
@@ -54,6 +54,7 @@ def run_events(webhook)
           run_events_for_issue_deleted if issue_deleted?
           run_events_for_issue_new_comment if issue_new_comment?
           run_events_for_issue_changelog if issue_changelog?
+          run_events_for_bug_without_cause if bug_without_cause?
```
Comment (rchampourlier) [inline lib/job_tomate/triggers/webhooks/jira.rb]: In the way I thought of the architecture, `bug_without_cause` would not be an event. You would instead reuse the more generic `IssueUpdatedStatus` [event](https://github.com/jobteaser/job_tomate/blob/master/lib/job_tomate/events/jira/issue_updated_status.rb).

So most of what you put in the event would be moved to your `SlackNotifyJIRABugIssueWithoutCauseUpdated`.

File: lib/job_tomate/actions/slack_notify_jira_bug_issue_without_cause_updated.rb (hunk 1 above)
Comment (marinados) [inline lib/job_tomate/actions/slack_notify_jira_bug_issue_without_cause_updated.rb]: i meant that every bug should should have a cause updated, but you're right that technically it's the issue that is updated and there's no cause. Anyway, done :)

**Comment by marinados** [comment]
I might have misunderstood the idea but it looks like there're some contradictory conditions in `JIRAUpdateIssueAssigneeAndRolesForStatus`. Since the re-assignment of the issue is happening after the `issue`object has been initialized, I wanted to update it using the new information. 
But I'm really confused about when the unassignment is happening, so it would be cool if we could see that together.

File: lib/job_tomate/actions/jira_update_issue_assignee_and_roles_for_status.rb [hunk 3]
```diff
@@ -116,10 +116,13 @@ def update_assignee_and_role(issue, user, role)
 
       def unassign(issue)
         update_issue(issue, fields: { assignee: nil })
+        issue.change_assignee_name(nil)
```
Comment (rchampourlier) [inline lib/job_tomate/actions/jira_update_issue_assignee_and_roles_for_status.rb]: I think I understand what you didn't ;) `issue` is a value-object. I think it should be immutable, it would make it clearer that this line is not useful. You're changing `issue` but it's only changing the value object which is not used anymore.

It's a bit different from usual Rails code as you're not using model objects (like AR models) to trigger updates, instead we're using command objects (like what gets called in `update_issue`) to trigger updates. More in the sense of the CQRS pattern.

If that's still not clear, let's discuss it and see how to make this more explicit in the code!

File: lib/job_tomate/actions/slack_notify_jira_bug_issue_updated_without_cause.rb [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+        return if issue.assignee_user.nil?
+        if issue.assignee_user.slack_username.blank?
+          LOGGER.warn "unknown Slack username for user ##{issue.assignee_user.id}"
+          return
+        end
+
+        send_message(issue)
+      end
+
+      def send_message(issue)
```
Comment (rchampourlier) [inline lib/job_tomate/actions/slack_notify_jira_bug_issue_updated_without_cause.rb]: I would make `send_message` private to clarify that it's not part of the object's public API.

File: lib/job_tomate/triggers/webhooks/jira.rb [hunk 5]
```diff
@@ -68,13 +68,17 @@ def issue_deleted?
           webhook_event == "issue_deleted"
         end
 
+        def issue_updated?
+          webhook_event == "issue_updated"
+        end
+
         def issue_new_comment?
-          return false unless webhook_event == "issue_updated"
+          return false unless issue_updated?
```
Comment (rchampourlier) [inline lib/job_tomate/triggers/webhooks/jira.rb]: Nice touch 👍

File: lib/job_tomate/values/jira/issue.rb [hunk 6]
```diff
@@ -116,6 +125,15 @@ def user_for_name(username)
           fail Errors::JIRA::UnknownUser, "no user with jira_username == \"#{username}\"" if user.nil?
           user
         end
+
+        def bug?
+          issue_type == "Bug"
+        end
+
+        # customfield_11101 corresponds to `bug_cause`
```
Comment (rchampourlier) [inline lib/job_tomate/values/jira/issue.rb]: Is this comment useful?

File: lib/job_tomate/actions/jira_update_issue_assignee_and_roles_for_status.rb (hunk 3 above)
Comment (marinados) [inline lib/job_tomate/actions/jira_update_issue_assignee_and_roles_for_status.rb]: i've just googled CQRS, haven't seen it before :) Looks curious!
i'd like 5mins to discuss how to best handle the changes brought by the `actions` module (like issue re-assignment) -- and who exactly should be notified on potential problems like missing bug cause. Should it always be the assignee no matter the issue status or always the assigned developer?

**Comment by rchampourlier** [comment]
To select the user to notify, take the user that perform the status change.

File: spec/acceptance/jira/change_issue_status_spec.rb [hunk 7]
```diff
@@ -159,4 +161,65 @@
       end
     end
   end
+
+  context "for a bug issue and" do
```
Comment (rchampourlier) [inline spec/acceptance/jira/change_issue_status_spec.rb]: Maybe also test the case where it's not a bug, nothing is sent.

File: spec/acceptance/jira/change_issue_status_spec.rb [hunk 8]
```diff
@@ -14,13 +14,15 @@
...
+  let(:slack_username) { 'user.name' }
 
   let!(:user) do
     JobTomate::Data::User.create(
       jira_username: jira_username,
       jira_developer: user_is_developer,
       jira_reviewer: user_is_reviewer,
-      jira_feature_owner: user_is_feature_owner
+      jira_feature_owner: user_is_feature_owner,
+      slack_username: slack_username
```
Comment (rchampourlier) [inline spec/acceptance/jira/change_issue_status_spec.rb]: Changing the slack user receiving the notification to the user that performed the status change on JIRA

File: spec/acceptance/jira/change_issue_status_spec.rb [hunk 9]
```diff
@@ -159,4 +161,65 @@
...
+Please do something about it! #{issue_link} (#{changelog_to_string})",
+          channel: "@#{slack_username}",
+          username: "Bug Monster",
+          icon_emoji: ":smiling_imp:"
+        }.to_json
+      end
+
+      it "the bug cause field is empty" do
+        stub_slack = stub_slack_request(expected_slack_body)
+        receive_stored_webhook(webhook_for_slack_notification)
```
Comment (rchampourlier) [inline spec/acceptance/jira/change_issue_status_spec.rb]: Here you may use the `block` in 

```
  def receive_stored_webhook(name_or_webhook, &block)
```

to customize the loaded webhook
